theme: jekyll-theme-minimal
title: My personal Git 
author:
  name: rotemarie
  email: rotem29@gmail.com


description: >
  

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
